---
name: Create Archive
on:
  create:
    tags:
      - 'v*'
jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@master
      - name: Archive Release
        uses: thedoctor0/zip-release@master
        with:
          filename: 'particle-docs.alfredworkflow'
          exclusions: '*.git* *img/ test*'
      - name: Upload Release
        uses: ncipollo/release-action@v1
        with:
          artifacts: "particle-docs.alfredworkflow"
          token: ${{ secrets.GITHUB_TOKEN }}
